/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as MoodTrackRouteImport } from './routes/mood.track'
import { Route as CalendarTimestampRouteImport } from './routes/calendar.$timestamp'
import { Route as TasksIdEditRouteImport } from './routes/tasks.$id.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodTrackRoute = MoodTrackRouteImport.update({
  id: '/mood/track',
  path: '/mood/track',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarTimestampRoute = CalendarTimestampRouteImport.update({
  id: '/$timestamp',
  path: '/$timestamp',
  getParentRoute: () => CalendarRoute,
} as any)
const TasksIdEditRoute = TasksIdEditRouteImport.update({
  id: '/tasks/$id/edit',
  path: '/tasks/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/calendar/$timestamp': typeof CalendarTimestampRoute
  '/mood/track': typeof MoodTrackRoute
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/calendar/$timestamp': typeof CalendarTimestampRoute
  '/mood/track': typeof MoodTrackRoute
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/calendar/$timestamp': typeof CalendarTimestampRoute
  '/mood/track': typeof MoodTrackRoute
  '/tasks/new': typeof TasksNewRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/calendar/$timestamp'
    | '/mood/track'
    | '/tasks/new'
    | '/tasks/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/calendar/$timestamp'
    | '/mood/track'
    | '/tasks/new'
    | '/tasks/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/calendar/$timestamp'
    | '/mood/track'
    | '/tasks/new'
    | '/tasks/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  MoodTrackRoute: typeof MoodTrackRoute
  TasksNewRoute: typeof TasksNewRoute
  TasksIdEditRoute: typeof TasksIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/track': {
      id: '/mood/track'
      path: '/mood/track'
      fullPath: '/mood/track'
      preLoaderRoute: typeof MoodTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$timestamp': {
      id: '/calendar/$timestamp'
      path: '/$timestamp'
      fullPath: '/calendar/$timestamp'
      preLoaderRoute: typeof CalendarTimestampRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/tasks/$id/edit': {
      id: '/tasks/$id/edit'
      path: '/tasks/$id/edit'
      fullPath: '/tasks/$id/edit'
      preLoaderRoute: typeof TasksIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CalendarRouteChildren {
  CalendarTimestampRoute: typeof CalendarTimestampRoute
}

const CalendarRouteChildren: CalendarRouteChildren = {
  CalendarTimestampRoute: CalendarTimestampRoute,
}

const CalendarRouteWithChildren = CalendarRoute._addFileChildren(
  CalendarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  MoodTrackRoute: MoodTrackRoute,
  TasksNewRoute: TasksNewRoute,
  TasksIdEditRoute: TasksIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
