/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoodTrackRouteImport } from './routes/mood.track'
import { Route as CalendarTimestampRouteImport } from './routes/calendar.$timestamp'
import { Route as TasksIdEditRouteImport } from './routes/tasks.$id.edit'
import { Route as HabitsIdStatsRouteImport } from './routes/habits.$id.stats'
import { Route as HabitsIdEditRouteImport } from './routes/habits.$id.edit'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodTrackRoute = MoodTrackRouteImport.update({
  id: '/mood/track',
  path: '/mood/track',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarTimestampRoute = CalendarTimestampRouteImport.update({
  id: '/$timestamp',
  path: '/$timestamp',
  getParentRoute: () => CalendarRoute,
} as any)
const TasksIdEditRoute = TasksIdEditRouteImport.update({
  id: '/tasks/$id/edit',
  path: '/tasks/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIdStatsRoute = HabitsIdStatsRouteImport.update({
  id: '/habits/$id/stats',
  path: '/habits/$id/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIdEditRoute = HabitsIdEditRouteImport.update({
  id: '/habits/$id/edit',
  path: '/habits/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/calendar/$timestamp': typeof CalendarTimestampRoute
  '/mood/track': typeof MoodTrackRoute
  '/habits/$id/edit': typeof HabitsIdEditRoute
  '/habits/$id/stats': typeof HabitsIdStatsRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/calendar/$timestamp': typeof CalendarTimestampRoute
  '/mood/track': typeof MoodTrackRoute
  '/habits/$id/edit': typeof HabitsIdEditRoute
  '/habits/$id/stats': typeof HabitsIdStatsRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/calendar/$timestamp': typeof CalendarTimestampRoute
  '/mood/track': typeof MoodTrackRoute
  '/habits/$id/edit': typeof HabitsIdEditRoute
  '/habits/$id/stats': typeof HabitsIdStatsRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/calendar'
    | '/dashboard'
    | '/new'
    | '/calendar/$timestamp'
    | '/mood/track'
    | '/habits/$id/edit'
    | '/habits/$id/stats'
    | '/tasks/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/calendar'
    | '/dashboard'
    | '/new'
    | '/calendar/$timestamp'
    | '/mood/track'
    | '/habits/$id/edit'
    | '/habits/$id/stats'
    | '/tasks/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/calendar'
    | '/dashboard'
    | '/new'
    | '/calendar/$timestamp'
    | '/mood/track'
    | '/habits/$id/edit'
    | '/habits/$id/stats'
    | '/tasks/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  CalendarRoute: typeof CalendarRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  NewRoute: typeof NewRoute
  MoodTrackRoute: typeof MoodTrackRoute
  HabitsIdEditRoute: typeof HabitsIdEditRoute
  HabitsIdStatsRoute: typeof HabitsIdStatsRoute
  TasksIdEditRoute: typeof TasksIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/track': {
      id: '/mood/track'
      path: '/mood/track'
      fullPath: '/mood/track'
      preLoaderRoute: typeof MoodTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$timestamp': {
      id: '/calendar/$timestamp'
      path: '/$timestamp'
      fullPath: '/calendar/$timestamp'
      preLoaderRoute: typeof CalendarTimestampRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/tasks/$id/edit': {
      id: '/tasks/$id/edit'
      path: '/tasks/$id/edit'
      fullPath: '/tasks/$id/edit'
      preLoaderRoute: typeof TasksIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/$id/stats': {
      id: '/habits/$id/stats'
      path: '/habits/$id/stats'
      fullPath: '/habits/$id/stats'
      preLoaderRoute: typeof HabitsIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/$id/edit': {
      id: '/habits/$id/edit'
      path: '/habits/$id/edit'
      fullPath: '/habits/$id/edit'
      preLoaderRoute: typeof HabitsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CalendarRouteChildren {
  CalendarTimestampRoute: typeof CalendarTimestampRoute
}

const CalendarRouteChildren: CalendarRouteChildren = {
  CalendarTimestampRoute: CalendarTimestampRoute,
}

const CalendarRouteWithChildren = CalendarRoute._addFileChildren(
  CalendarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  CalendarRoute: CalendarRouteWithChildren,
  DashboardRoute: DashboardRoute,
  NewRoute: NewRoute,
  MoodTrackRoute: MoodTrackRoute,
  HabitsIdEditRoute: HabitsIdEditRoute,
  HabitsIdStatsRoute: HabitsIdStatsRoute,
  TasksIdEditRoute: TasksIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
